/**
 * Maintainer's Ed25519 public key for verifying update-feed signatures.
 *
 * Generated by the maintainer; private key lives in a secrets manager
 * (1Password / GitHub Encrypted Secrets / vault). Replace this empty
 * placeholder with the real base64-encoded raw 32-byte public key BEFORE
 * shipping the first release with this feature enabled.
 *
 * Key rotation policy: ship a new app version with a new constant. Old
 * installs continue trusting the previous key until they upgrade. There
 * is no online revocation list.
 *
 * Generation procedure:
 *   openssl genpkey -algorithm Ed25519 -out update-feed-private.pem
 *   openssl pkey -in update-feed-private.pem -pubout -outform DER \
 *     | tail -c 32 | base64
 *
 * The `tail -c 32` strips the DER SubjectPublicKeyInfo prefix, leaving
 * just the raw 32-byte Ed25519 public key suitable for Web Crypto's
 * `subtle.importKey("raw", ...)`.
 */
export const UPDATE_FEED_PUBLIC_KEY_BASE64 = "";

/**
 * Returns true when a public key constant has been configured.
 * Empty / whitespace-only is treated as "not configured" and the
 * update-check returns "disabled" rather than trying to verify.
 */
export function isPublicKeyConfigured(): boolean {
  return UPDATE_FEED_PUBLIC_KEY_BASE64.trim().length > 0;
}

/**
 * Import the bundled public key as a CryptoKey for `subtle.verify`.
 * Throws when the constant is empty or malformed — callers should
 * gate on `isPublicKeyConfigured()` first.
 *
 * @param _keyBase64Override - test-only injection seam; production callers omit this.
 */
export async function importUpdateFeedPublicKey(_keyBase64Override?: string): Promise<CryptoKey> {
  const b64 = (_keyBase64Override ?? UPDATE_FEED_PUBLIC_KEY_BASE64).trim();
  if (b64.length === 0) {
    throw new Error("UPDATE_FEED_PUBLIC_KEY_BASE64 is not configured");
  }
  const rawKey = Buffer.from(b64, "base64");
  if (rawKey.length !== 32) {
    throw new Error(`UPDATE_FEED_PUBLIC_KEY_BASE64 must decode to 32 bytes (got ${rawKey.length})`);
  }
  return crypto.subtle.importKey(
    "raw",
    rawKey,
    { name: "Ed25519" },
    false, // not extractable
    ["verify"],
  );
}
