import { join } from "node:path";
import type Database from "better-sqlite3";
import { migrate as drizzleMigrate } from "drizzle-orm/better-sqlite3/migrator";
import { initArtifactsFtsStore, openDb } from "./index.js";

export interface MigrateOptions {
  path?: string;
  migrationsFolder?: string;
}

/**
 * Apply all pending migrations to the database.
 * Migrations are generated by drizzle-kit into the `drizzle/` folder.
 *
 * Post-schema-migration data hooks run here as well (e.g., Phase 17
 * renaming kind:"multiple-choice" → "single-choice" in items_json).
 */
export function runMigrations(opts: MigrateOptions = {}): { applied: number; path: string } {
  const dbOpts: import("./index.js").OpenDbOptions = opts.path ? { path: opts.path } : {};
  const { db, path, sqlite } = openDb(dbOpts);
  const folder = opts.migrationsFolder ?? join(process.cwd(), "drizzle");
  drizzleMigrate(db, { migrationsFolder: folder });

  // Post-migration: initialize FTS5 virtual tables for notes + flashcards.
  // Called here (not in openDb) because FTS5 content= tables require the
  // backing tables (notes, flashcards) to already exist.
  initArtifactsFtsStore(sqlite);

  // Phase 17 data migration: rename kind:"multiple-choice" → "single-choice"
  // inside assignments.items_json blobs.
  // This is idempotent — items already migrated have "single-choice" and
  // the JSON.replace won't touch them.
  rewriteMultipleChoiceToSingleChoice(sqlite);

  return { applied: -1, path }; // drizzle's migrator does not return count; -1 signals "applied"
}

/**
 * Phase 17: rewrite `kind:"multiple-choice"` to `kind:"single-choice"` in
 * all assignments.items_json blobs. Uses a Node-side row walk rather than
 * SQLite's json_each (which isn't available without a custom build) to keep
 * the migration simple and readable.
 *
 * Idempotent: running multiple times is safe. Already-migrated items have
 * `"single-choice"` and won't be modified.
 */
function rewriteMultipleChoiceToSingleChoice(sqlite: Database.Database): void {
  const rows = sqlite
    .prepare<[], { id: string; items_json: string }>(
      "SELECT id, items_json FROM assignments WHERE items_json LIKE '%\"multiple-choice\"%'",
    )
    .all();

  if (rows.length === 0) return;

  const update = sqlite.prepare<[string, string], void>(
    "UPDATE assignments SET items_json = ? WHERE id = ?",
  );

  const runAll = sqlite.transaction(() => {
    let migrated = 0;
    for (const row of rows) {
      // biome-ignore lint/suspicious/noExplicitAny: JSON blob — shape validated by schema
      let items: any[];
      try {
        items = JSON.parse(row.items_json);
      } catch {
        // Skip malformed rows — don't blow up the migration.
        continue;
      }
      let changed = false;
      for (const item of items) {
        if (item && item.kind === "multiple-choice") {
          item.kind = "single-choice";
          changed = true;
        }
      }
      if (changed) {
        update.run(JSON.stringify(items), row.id);
        migrated++;
      }
    }
    return migrated;
  });

  const count = runAll();
  if (count > 0) {
    console.log(
      `Phase 17 migration: rewrote ${count} assignment(s) from multiple-choice to single-choice.`,
    );
  }
}
