import { join } from "node:path";
import { migrate as drizzleMigrate } from "drizzle-orm/better-sqlite3/migrator";
import { openDb } from "./index.js";

export interface MigrateOptions {
  path?: string;
  migrationsFolder?: string;
}

/**
 * Apply all pending migrations to the database.
 * Migrations are generated by drizzle-kit into the `drizzle/` folder.
 */
export function runMigrations(opts: MigrateOptions = {}): { applied: number; path: string } {
  const dbOpts: import("./index.js").OpenDbOptions = opts.path ? { path: opts.path } : {};
  const { db, path } = openDb(dbOpts);
  const folder = opts.migrationsFolder ?? join(process.cwd(), "drizzle");
  drizzleMigrate(db, { migrationsFolder: folder });
  return { applied: -1, path }; // drizzle's migrator does not return count; -1 signals "applied"
}
